sudo: false

language: node_js

node_js:
  - 'iojs'
  - '0.12'

script:
    - npm run task ci

after_success:
#    - npm run task coveralls
    - brew update
    - brew install influxdb
    - npm test_system