sudo: false

language: node_js

node_js:
  - 'iojs'
  - '0.12'

before_install:
    - wget http://influxdb.s3.amazonaws.com/influxdb_0.9.4.1_amd64.deb
    - dpkg-deb -x influxdb_0.9.4.1_amd64.deb $HOME
    - dpkg-deb -c influxdb_0.9.4.1_amd64.deb
#    - $HOME/opt/influxdb/versions/0.9.0/influxd

script:
    - npm run task ci
    - npm run test_system

after_success:
#    - npm run task coveralls