sudo: false

language: node_js

addons:
  firefox: "41.0"

node_js:
  - 'iojs'
  - '0.12'

before_install:
    - wget http://influxdb.s3.amazonaws.com/influxdb_0.9.4.2_amd64.deb
    - dpkg-deb -x influxdb_0.9.4.2_amd64.deb $HOME
    - $HOME/opt/influxdb/versions/0.9.4.2/influxd > $HOME/influx.log 2>&1 &

script:
    - npm run task ci
    - npm run test_system

after_success:
#    - npm run task coveralls

after_script:
    - cat $HOME/influx.log

