#sudo: false

language: node_js

node_js:
  - 'iojs'
  - '0.12'

before_install:
    - wget http://s3.amazonaws.com/influxdb/influxdb_latest_amd64.deb
    - sudo dpkg -i influxdb_latest_amd64.deb
    - sudo service influxdb start

script:
    - npm run task ci
    - npm run test_system

after_success:
#    - npm run task coveralls