sudo: false

language: node_js

addons:
  firefox: "41.0"

node_js:
  - '4.1'
  - '0.12'
  - '5'

before_install:
    - wget http://influxdb.s3.amazonaws.com/influxdb_0.9.4.2_amd64.deb
    - dpkg-deb -x influxdb_0.9.4.2_amd64.deb $HOME
    - $HOME/opt/influxdb/versions/0.9.4.2/influxd --config $TRAVIS_BUILD_DIR/test/system/influxdb.conf > $HOME/influx.log 2>&1 &
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - sleep 3 # give xvfb some time to start
    # - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"

script:
    - npm run task ci
    - npm run test_system

after_success:
#    - npm run task coveralls

after_script:
    - cat $HOME/influx.log

